stages:
  - 🔨 build
  - 🚀 deploy

# job pour construction image docker
.docker-build:
  image: docker:stable-dind
  stage: 🔨 build
  variables:
    BUILD_CONTEXT: "."
    IMAGE: ""
  script:
    - echo $IMAGE
    - echo $CI_COMMIT_TAG
    - >
      if [[ "$CI_COMMIT_TAG" == "" ]]; then
        echo "TAG VIDE";
        IMAGE_BUILD=${IMAGE}/${CI_COMMIT_REF_NAME};
        VERSION_IMAGE=${CI_COMMIT_SHA:0:8}-snapshot;
      else
        echo "TAG PAS VIDE";
        IMAGE_BUILD=${IMAGE};
        VERSION_IMAGE=${CI_COMMIT_REF_NAME};
      fi
    - echo ${VERSION_IMAGE}
    - echo ${IMAGE_BUILD}
    - docker build -f ${BUILD_CONTEXT}/Dockerfile -t ${IMAGE_BUILD} ${BUILD_CONTEXT}
    - echo ${REGISTRY_PASSWORD} | docker login ${REGISTRY} -u ${REGISTRY_USER} --password-stdin
    - docker tag ${IMAGE_BUILD} ${IMAGE_BUILD}:${VERSION_IMAGE}
    - echo "push ${IMAGE_BUILD}:${VERSION_IMAGE}" && docker push ${IMAGE_BUILD}:${VERSION_IMAGE}


🔨 buildFocus:
  extends: .docker-build
  variables:
    BUILD_CONTEXT: "."  
    IMAGE: "${REGISTRY}focus-marches"

🔨 buildBatchFocus:
  extends: .docker-build
  variables:
    IMAGE: "${REGISTRY}focus-marches-batch"
    BUILD_CONTEXT: "batch"


#🚀 deployBDD:
#  stage:
#    🚀 deploy
#  only:
#    - master
#  variables:
#    COMPOSE_FILE: "~/app/compose/database.yml"
#    STACK: focus
#  script:
#    - ssh $USER@$SERVER "docker network create -d overlay --attachable app_network || true"
#    - ssh $USER@$SERVER "docker stack deploy -c ${COMPOSE_FILE:?} ${STACK:?}"
#
#🚀 deployFocus:
#  stage:
#    🚀 deploy
#  needs: [ 🔨 buildFocus ]
#  only:
#    - master
#  variables:
#    COMPOSE_FILE: "~/app/compose/focus-marches.yml"
#    STACK: focus
#  script:
#    - ssh $USER@$SERVER "docker network create -d overlay --attachable app_network || true"
#    - ssh $USER@$SERVER "REGISTRY=${REGISTRY} BRANCH=${CI_COMMIT_BRANCH} CI_COMMIT=${CI_COMMIT_SHORT_SHA} docker stack deploy --with-registry-auth -c ${COMPOSE_FILE:?} ${STACK:?}"
