version: "3.7"
services:
  database:
    image: ${MARIADB_IMAGE}
    environment:
      MARIADB_DATABASE : ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${HOST_DB_PORT}:3306"
    expose:
      - '3306'
    volumes:
      - ${MARIADB_DATA}:/var/lib/mysql
      - ${HOST_APP_FOLDER}/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ${HOST_APP_FOLDER}/sql/data.sql:/docker-entrypoint-initdb.d/2.sql
      - ${HOST_APP_FOLDER}/sql/index.sql:/docker-entrypoint-initdb.d/3.sql

  focus-marches:
    build: ${HOST_APP_FOLDER}
    image: ${FOCUS_MARCHE_IMAGE_NAME}
    ports:
      - "${HOST_FOCUS_PORT}:3306"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 5
        delay: 0s
      update_config:
        parallelism: 1
        delay: 0s
        order: stop-first
        failure_action: pause
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
volumes:
  focus-db:
