version: "3.7"
services:
  database:
    image: mariadb:10.4
    environment:
      MARIADB_DATABASE : 'marches_publics'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      MARIADB_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - focus-db:/var/lib/mysql
volumes:
  focus-db:

networks:
  default:
    external: true
    name: app_network
