version: "3.7"

services:
  focus-marches:
    image: ${REGISTRY}csm/focus-marches/${BRANCH}:${CI_COMMIT}
    ports:
      - '80:80'
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 5
        delay: 0s
      update_config:
        parallelism: 1
        delay: 0s
        order: stop-first
        failure_action: pause
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
#      labels:
#        - "traefik.enable=true"
#        - "traefik.docker.network=traefik_network"
#        - "traefik.http.routers.alertmanager.rule=Host(`focus-marches.csm.ovh`)"
#        - "traefik.http.routers.alertmanager.tls=true"
#        - "traefik.http.routers.alertmanager.tls.certresolver=myresolver"
#        - "traefik.http.services.alertmanager.loadbalancer.server.port=80"
